[project]
name = "simple-calculator"
version = "0.1.0"
description = "Simple realisation of a working calculator (similar to the Windows version) in PyQt6"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pyqt6>=6.9.1"]
